// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcBbOVusdsKkWG96BbP5MjlHW3c3aIro',
    appId: '1:687939878080:web:c30bc88bb5b363c324c125',
    messagingSenderId: '687939878080',
    projectId: 'miaged-dd8f4',
    authDomain: 'miaged-dd8f4.firebaseapp.com',
    storageBucket: 'miaged-dd8f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXI_rzVyllwVCKYGNeoSYVmXPLJDGFafY',
    appId: '1:687939878080:android:84a038f26a884e2524c125',
    messagingSenderId: '687939878080',
    projectId: 'miaged-dd8f4',
    storageBucket: 'miaged-dd8f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF1dL6oKfBU8VJHr0Tf5wyCQlJ7qTKBIA',
    appId: '1:687939878080:ios:b9e4dd94f6612eeb24c125',
    messagingSenderId: '687939878080',
    projectId: 'miaged-dd8f4',
    storageBucket: 'miaged-dd8f4.appspot.com',
    iosClientId: '687939878080-9ds8ktec4l6uccrhddepcui2ils8c95b.apps.googleusercontent.com',
    iosBundleId: 'com.example.miagedprojet',
  );
}
